force-app/main/default/objects/Guest_Detail__c/fields/Adults__c.field-meta.xml
<CustomField>
    <fullName>Adults__c</fullName>
    <label>Adults</label>
    <type>Number</type>
    <precision>3</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/objects/Guest_Detail__c/fields/Check_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Date__c</fullName>
    <label>Check In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Guest_Detail__c/fields/Check_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Date__c</fullName>
    <label>Check Out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Guest_Detail__c/fields/Children__c.field-meta.xml
<CustomField>
    <fullName>Children__c</fullName>
    <label>Children</label>
    <type>Number</type>
    <precision>3</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/classes/GuestEntryController.cls
public with sharing class GuestEntryController {

    @AuraEnabled
    public static Id saveGuest(
     String firstName,
     String lastName,
     String email,
     String phone,
     Id hotelId,
     String checkIn,
     String checkOut,
     Integer adults,
     Integer children
    ){
     Guest_Detail__c g = new Guest_Detail__c();
         g.Guest_First_Name__c = firstName;
         g.Guest_Last_Name__c = lastName;
         g.Guest_Email__c = email;
         g.Guest_Phone__c = phone;
         g.Hotel__c = hotelId;
         if(String.isNotBlank(checkIn))  g.Check_In_Date__c  = Date.valueOf(checkIn);
         if(String.isNotBlank(checkOut)) g.Check_Out_Date__c = Date.valueOf(checkOut);
         g.Adults__c   = adults   != null ? adults   : 1;
         g.Children__c = children != null ? children : 0;
     insert g;
     return g.Id;
    }
}